# This file was automatically converted from Perl to Python
# by the Perl to Python Conversion Agent
# Conversion date: 2025-08-09 22:46:29
# Note: This is an automated conversion and may require manual review

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Perl to Python Converter

import os
import sys
from StringUtils import to_uppercase
# Add current directory to module search path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

if __name__ == '__main__':
    try:
        # Add current directory to module search path


        # Test input
        input = "hello world"

        # Convert and print
        output = to_uppercase(input)
    print(f"Uppercase: {output}\n")
    except ValueError as e:
        print(f"Value Error: {e}")
    raise
    except FileNotFoundError as e:
        print(f"File Error: {e}")
    raise
    except Exception as e:
        print(f"Error: {e}")
        raise